#!/usr/bin/sh

modprobe kathrein_micom paramDebug=0

if [ -e /var/etc/.firstboot ]; then
   echo "WAIT 3 min" > /dev/vfd
   echo "WAIT 3 min"
   rm /var/etc/.firstboot
   touch /dev/.devfsd
fi

if [ -e /etc/init.d/mountvirtfs ]; then
   /etc/init.d/mountvirtfs start
fi

modprobe e2_proc

if [ ! -e /var/etc/.firstboot ]; then

   echo "Starting DEBUG Interface"
if [ -e /etc/init.d/mountall ]; then
   /etc/init.d/mountall start
fi

   echo "init stmfb"
   modprobe stmcore-display-stx7109c3
   modprobe stmfb display0=720x576-32@60:10m:pal:yuv:yuv;# display1=720x576-16@50:1m:pal:cvbs;

   echo "LOADING MODULES"   
   fp_control -c
   fp_control -t "LOADING MODULES"

   echo "load a/v firmware"
   /usr/bin/ustslave /dev/st231-1 /boot/audio.elf
   /usr/bin/ustslave /dev/st231-0 /boot/video.elf

   echo "init embx"
   modprobe embxshell
   modprobe embxmailbox mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0 ;
   modprobe embxshm mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000 ;
   modprobe mme_host transport0=shm

   echo "init AVS"
   modprobe avs type=stv6412

   player=`cat /proc/stb/player/version`
   if [ $player=='player179' ]; then
     echo "init player 179"
   else
     echo "init player 131"
   fi
   modprobe mmelog
   modprobe mpeg2hw mmeName=MPEG2_TRANSFORMER0;
   modprobe ksound
   modprobe p2div64
   modprobe stm_v4l2
   if [ $player=='player179' ]; then
     modprobe stmvout
     modprobe stmvbi
   fi
   modprobe pseudocard

   modprobe cx21143
   modprobe ufc960_cic
   if [ $player=='player179' ]; then
     modprobe pti
     modprobe stm_monitor
     modprobe stmsysfs
     modprobe stmdvb
   else
     modprobe pti
     modprobe stmdvb
     modprobe stm_monitor
   fi
   modprobe player2
   modprobe sth264pp
   modprobe stmalloc
   modprobe platform
   modprobe silencegen

   showiframe -p /usr/share/bootlogo.mvi &
   stfbcontrol a 0

   echo "init frontpanel"
   modprobe boxtype
   modprobe simu_button

   mknod /dev/rc c 147 1 

   #params:
   #toggleFeedback 0 = false, 1 = true
   #disableFeed
   #period
   #delay
   /usr/bin/evremote2 0 0 10 120 &

   #fix this later if we got to manage a marusys raw device driver
   mount /dev/sda5 /hdd/

   if [ -e /etc/init.d/portmap ]; then
   /etc/init.d/portmap start
fi
if [ -e /etc/init.d/vsftpd ]; then
   /etc/init.d/vsftpd start
fi
   /usr/sbin/inetd

   #timefix e2
   date -s "121220001970"

   stfbcontrol a 255

   fp_control -t "LOADING e2"
   echo "LOADING e2"

   until false
   do
      echo "starting e2->"
      /usr/bin/enigma2
      rtv=$?
      echo "e2 ended <- RTV: " $rtv
     case "$rtv" in
		0) echo "0"
		   echo "E2 ERROR"
      	   init 6;;
		1) echo "1"
		   echo "SHUTDOWN"
		   init 0;;
		2) echo "2"
		   echo "REBOOT"
		   init 6;;
		3) echo "3"
		   echo "E2 RESTART"
		   echo "0" > /proc/progress
		   showiframe -p /usr/share/bootlogo.mvi &;;
		*) echo "*"
		   echo "ERROR"
           init 6;;
      esac
   done 
fi
