#!/usr/bin/sh
#Version 190125.1

echo "Fortis HS7810A Enigma2"

modprobe e2_proc

echo "[rcS] Init frontpanel"
if [ ! -e /dev/vfd ]; then
   mknod -m 0660 /dev/vfd c 147 0
fi
modprobe nuvoton
modprobe simu_button

if [ -e /var/etc/.firstboot ]; then
   echo "1min" > /dev/vfd
   echo "[rcS] WAIT 1 minute"
   rm /var/etc/.firstboot
   sleep 1
   touch /dev/.devfsd
else
   echo "LD10" > /dev/vfd
   echo "[rcS] LOAD 10"
fi

if [ -e /etc/init.d/mountvirtfs ]; then
   /etc/init.d/mountvirtfs start
fi

echo "[rcS] Starting automounter"
if [ -e /etc/init.d/autofs ]; then
   /etc/init.d/autofs start
fi

echo "[rcS] Starting DEBUG Interface"
if [ -e /etc/init.d/mountall ]; then
   /etc/init.d/mountall start
fi

echo "[rcS] Init stmfb (LOAD 9)"
echo "LD 9" > /dev/vfd
modprobe stmcore-display-sti7111

if grep -q "config.av.videoport=Scart" /etc/enigma2/settings; then
   modprobe stmfb display0=720x576i-32@50:12m:pal:rgb:rgb #SCART
else
   modprobe stmfb display0=1280x720-32@50:12m:pal:rgb:rgb #HDMI
fi

echo "[rcS] Loading modules"

echo "[rcS] Load audio firmware (LOAD 8)"
echo "LD 8" > /dev/vfd
dtsdown=`cat /etc/enigma2/settings | grep systemoptions.dtsdownmix | cut -d "=" -f2`
if [ ! $dtsdown ] && [ -e /boot/audio_dts.elf ]; then
   /usr/bin/ustslave /dev/st231-1 /boot/audio_dts.elf > /dev/null
else
   /usr/bin/ustslave /dev/st231-1 /boot/audio.elf > /dev/null
fi

echo "[rcS] Load video firmware (LOAD 7)"
echo "LD 7" > /dev/vfd
/usr/bin/ustslave /dev/st231-0 /boot/video.elf > /dev/null

echo "[rcS] Init embx (LOAD 6)"
echo "LD 6" > /dev/vfd
modprobe embxshell
modprobe embxmailbox mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0
modprobe embxshm mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000
modprobe mme_host transport0=shm

echo "[rcS] Init AVS (LOAD 5)"
echo "LD 5" > /dev/vfd
modprobe avs type=avs_pio

player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
echo "[rcS] Init player $player (LOAD 4)"
echo "LD 4" > /dev/vfd
modprobe mmelog
modprobe ksound
modprobe p2div64
modprobe stm_v4l2

modprobe pseudocard

echo "[rcS] Init frontend"
modprobe lnb type=a8293
modprobe stv090x paramDebug=0
mknod /dev/lnb c 149 0

echo "[rcS] Init CI & cardreader"
modprobe starci
modprobe smartcard
modprobe pti waitMS=20 videoMem=4096
if [ $? -ne 0 ]; then
   modprobe pti
   echo "[rcS] Simple pti"
else
   echo "[rcS] Full feature pti"
fi
modprobe stm_monitor
modprobe stmsysfs
modprobe stmdvb

echo "[rcS] Init player2 (LOAD 3)"
echo "LD 3" > /dev/vfd
modprobe player2
modprobe sth264pp
modprobe stmalloc
modprobe platform
modprobe silencegen

modprobe bpamem
mknod /dev/bpamem c 153 0

echo "[rcS] Init HDMI-CEC"
if [ -e /lib/modules/2.6.32.71_stm24_0217/extra/cec ];then
   modprobe cec activemode=1
fi

if [ -e /usr/share/bootlogo.mvi ]; then
   showiframe -p /usr/share/bootlogo.mvi &
fi

stfbcontrol a 0

if [ -e /lib/modules/2.6.32.71_stm24_0217/extra/exportfs ]; then
   echo "[rcS] Init exportfs"
   modprobe exportfs
fi

if [ -e /lib/modules/2.6.32.71_stm24_0217/extra/cifs ]; then
echo "[rcS] Init CIFS support"
   modprobe cifs
fi

if [ -e /lib/modules/2.6.32.71_stm24_0217/extra/ntfs ]; then
   echo "[rcS] Init NTFS support"
   modprobe ntfs
fi

if [ -e /lib/modules/2.6.32.71_stm24_0217/extra/tun ]; then
   echo "[rcS] Init tun support"
   modprobe tun
fi

if [ -e /lib/modules/2.6.32.71_stm24_0217/extra/usbserial ]; then
   modprobe usbserial
   if [ -e /lib/modules/2.6.32.71_stm24_0217/extra/ftdi ]; then
   echo "[rcS] Init FTDI USB serial support"
      modprobe ftdi
   fi
   if [ -e /lib/modules/2.6.32.71_stm24_0217/extra/pl2303 ]; then
   echo "[rcS] Init PL2303 USB serial support"
      modprobe pl2303
   fi
fi

echo "[rcS] Init remote control (LOAD 2)"
echo "LD 2" > /dev/vfd
/usr/bin/evremote2 10 140 &

stfbcontrol a 255

echo -n "[rcS] Init WLAN: "
wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
if [ ! $wlan ] || [ ! -e /lib/modules/2.6.32.71_stm24_0217/extra/$wlan ]; then
   echo "None."
else
   modprobe $wlan
   echo "$wlan"
#   echo "$wlan WLAN" > /dev/vfd
#   sleep 3
fi

# Handle SWAPPART and RECORD labels and USB devices
if [ -e /usr/sbin/amount.sh ]; then
   (sleep 20; /usr/sbin/amount.sh) &
fi

# Enable PKT plugins
if [ ! -e /tmp/reference.dat ] && [ -e /var/usr/bin/reference.dat ]; then
   cp /var/usr/bin/reference.dat /tmp
fi

echo "[rcS] Init portmap & ftp (LOAD 1)"
echo "LD 1" > /dev/vfd
if [ -e /etc/init.d/portmap ]; then
   /etc/init.d/portmap start
fi
if [ -e /etc/init.d/vsftpd ]; then
   /etc/init.d/vsftpd start
fi
/usr/sbin/inetd

# Do own extras
if [ -e /etc/ownscript.sh ]; then
   /etc/ownscript.sh &
fi

echo "[rcS] Loading E2"
echo "LDE2" > /dev/vfd

until false
do
   echo "[rcS] Entering e2 main loop"
   if [ -e /usr/share/backdrop.mvi ]; then
      showiframe -p /usr/share/backdrop.mvi &
   fi
   /usr/bin/enigma2
   rtv=$?
   echo "[rcS] e2 ended <- return value: " $rtv
   case "$rtv" in
      0) echo "[rcS] E2 ERROR"
         echo "E2Er" > /dev/vfd
         init 6;;
      1) echo "[rcS] SHUTDOWN"
         echo "Shdn" > /dev/vfd
         if [ -e /usr/share/shutdown.mvi ]; then
            showiframe -p /usr/share/shutdown.mvi &
         fi
         init 0;;
      2) echo "[rcS] REBOOT"
         echo "rebt" > /dev/vfd
         init 6;;
      3) echo "[rcS] E2 RESTART"
         echo "E2rS" > /dev/vfd
         echo "0" > /proc/progress
         if [ -e /usr/share/backdrop.mvi ]; then
            showiframe -p /usr/share/backdrop.mvi &
         else
            showiframe -p /usr/share/bootlogo.mvi &
         fi
         echo -n " ";;
      *) echo "[rcS] ERROR"
         echo "Err " > /dev/vfd
         init 6;;
   esac
done
