#!/usr/bin/sh

modprobe e2_proc
modprobe fp

if [ -e /var/etc/.firstboot ]; then
   rm /var/etc/.firstboot
   sleep 1
   echo "WAIT 3 min"
   echo "WAIT 3 min" > /dev/dbox/fp0
   touch /dev/.devfsd
fi

if [ -e /etc/init.d/mountvirtfs ]; then
   /etc/init.d/mountvirtfs start
fi

if [ -e /dev/ttyAS1 ]; then 
   rm -f /dev/ttyAS1 
fi 

if [ -e /etc/init.d/portmap ]; then
   /etc/init.d/portmap start
fi

/usr/bin/cubefpctl --syncsystime

if [ ! -e /var/etc/.firstboot ]; then
   echo "LOADING MODULES" > /dev/dbox/fp0
   echo "LOADING MODULES"   

   echo "init AVS"
   modprobe avs type=stv6412

   echo "init stmfb"
   modprobe stmcore-display-stx7109c3
   /usr/bin/cubefpctl --gettvmode
   TVMODE=$?
   case "$TVMODE" in
	0) echo "SD-PAL"
  	   modprobe stmfb display0=720x576-32@50:12m:pal:yuv:yuv;;
	1) echo "SD-NTSC"
	   modprobe stmfb display0=720x480-32@60:12m:ntsc-m:yuv:yuv;;
	2) echo "720P-50"
	   modprobe stmfb display0=1280x720-32@50:12m:pal:yuv:yuv;;
	3) echo "720P-60"
	   modprobe stmfb display0=1280x720-32@60:12m:ntsc-m:yuv:yuv;;
	4) echo "1080I-50"
	   modprobe stmfb display0=1920x1080-32@50i:12m:pal:yuv:yuv;;
	5) echo "1080I-60"
	   modprobe stmfb display0=1920x1080-32@60i:12m:ntsc-m:yuv:yuv;;
	*) echo "Use default SD-PAL"
	   modprobe stmfb display0=720x576-32@50:12m:pal:yuv:yuv;;
   esac

   echo "load a/v firmware"
   /usr/bin/ustslave /dev/st231-1 /boot/audio.elf
   /usr/bin/ustslave /dev/st231-0 /boot/video.elf

   echo "init embx"
   modprobe embxshell
   modprobe embxmailbox mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0 ;
   modprobe embxshm mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0xa4000000:0x10000000 ;
   modprobe mme_host transport0=shm

   echo "init player"
   modprobe mmelog
   modprobe mpeg2hw mmeName=MPEG2_TRANSFORMER1;
   modprobe ksound
   modprobe p2div64
   modprobe stm_v4l2
   modprobe pseudocard
   modprobe tuner
   modprobe starci
   modprobe pti
   modprobe stmdvb
   modprobe stm_monitor
   modprobe player2
   modprobe sth264pp
   modprobe stmalloc
   modprobe platform
   modprobe silencegen 

   echo "init frontpanel"
   modprobe boxtype
fi

showiframe -p /usr/share/bootlogo.mvi &
stfbcontrol a 0

if [ ! -e /var/etc/.firstboot ]; then
   echo "enigma2" > /dev/dbox/fp0
   echo "LOADING e2"

if [ -e /etc/init.d/mountall ]; then
   /etc/init.d/mountall start
fi

if [ -e /etc/init.d/vsftpd ]; then
   /etc/init.d/vsftpd start
fi
   /usr/sbin/inetd

   stfbcontrol a 255
   until false
   do
      /usr/bin/cubefpctl --setledoff
      echo "starting e2->"
      /usr/bin/enigma2
      rtv=$?
      echo "e2 ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo "E2 ERROR"
      		   init 6;;
		1) echo "1"
		   echo "SHUTDOWN"
		   echo "SHUTDOWN" > /dev/dbox/fp0
		   init 0;;
		2) echo "2"
		   echo "REBOOT"
		   init 6;;
		3) echo "3"
		   echo "E2 RESTART"
		   showiframe -p /usr/share/bootlogo.mvi &
		   echo "0" > /proc/progress;;
		*) echo "*"
		   echo "ERROR"
		   showiframe -p /usr/share/bootlogo.mvi &
		   echo "0" > /proc/progress;;
      esac
   done 
fi
