MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += "\
	firmware-carl9170 \
	firmware-htc7010 \
	firmware-htc9271 \
	firmware-mt7601u \
	firmware-rt2870 \
	firmware-rt73 \
	firmware-rt3070 \
	firmware-mt7601u \
	firmware-rtl8188eu \
	firmware-rtl8192cu \
	firmware-rtl8712u \
	firmware-rtl8xxxu \
    firmware-zd1211 \
	\
	kernel-module-ath \
	kernel-module-ar9170usb \
	kernel-module-rt2500usb \
	kernel-module-rt2800usb \
	kernel-module-rt2x00usb \
	kernel-module-rt2x00lib \
	kernel-module-rt73usb \
	kernel-module-rtl8187 \
	kernel-module-zd1211rw \
	\
	kernel-module-mt7601u \
	kernel-module-rt2870sta \
	kernel-module-rt3070sta \
	kernel-module-rt5370sta \
	kernel-module-rtl8188eu \
	kernel-module-rtl8192cu \
	kernel-module-rtl8192du \
	kernel-module-rtl8192eu \
	kernel-module-rtl871x \
	\
	rt7777-legacy \
    rt8812au \
	rtl8723a \
	rtl8723bs \
"
